accounts/urls.py
from django.urls import path
from django.contrib.auth import views

from accounts.views import SignUpView

urlpatterns = [
    # Вход
    path('login/', views.LoginView.as_view(), name='login'),

    # Выход
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # Сброс пароля
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Смена пароля
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Регистрация
    path('signup/', SignUpView.as_view(), name='registration'),
]

notes_page/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('note/create/', BlogCreateView.as_view(), name='post_new'),  # Здесь создается заметка
    path('note/<int:pk>/', BlogDetailView.as_view(), name='post_detail'), # Здесь мы можем просмотреть содержимое
    path('note/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'), # Здесь можно обновить заметку
    path('note/<int:pk>/delete/', BlogDeleteView.as_view(), name='post_delete'), # Здесь можно удалить заметку
    path('note/<int:pk>/complete/', CompleteView.as_view(), name='post_complete'), # Здесь можно удалить заметку
    path('', BlogListView.as_view(), name='home'),
    path('home_complete/', ListCompleteView.as_view(), name='home_complete'),
]

site_remember/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notes_page.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

notes_page/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Notes(models.Model):
    name = models.CharField(max_length=30, blank=False, verbose_name='Заголовок')
    descriptions = models.TextField(max_length=1000, blank=True, verbose_name='Описание')
    important = models.BooleanField(blank=True, verbose_name='Важно')
    time_create = models.DateTimeField(auto_now_add=True, blank=True)
    datecompleted = models.DateTimeField(null=True, blank=True, auto_now=True)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    task_complete = models.BooleanField(blank=True, default=False, verbose_name='Завершить задание')


    def __str__(self):
        return self.name

    def get_absolute_url(self):  # Тут мы создали новый метод
        return reverse('post_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

notes_page/forms.py
from django.forms import ModelForm
from django import forms
from .models import Notes

class NotesForm(ModelForm):

    class Meta:
        model = Notes
        fields = ['name', 'descriptions', 'important']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'descriptions': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 30}),
        }

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from accounts.forms import UserRegisterForm


class SignUpView(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

notes_page/views.py
from django.urls import reverse_lazy

from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView  # новое изменение
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import NotesForm
from .models import Notes


class BlogListView(LoginRequiredMixin, ListView):
    paginate_by = 5
    model = Notes
    template_name = 'notes_page/home.html'


class BlogDetailView(LoginRequiredMixin, UpdateView):
    model = Notes
    fields = ['task_complete']
    template_name = 'notes_page/post_detail.html'
    success_url = reverse_lazy('home')


class BlogCreateView(LoginRequiredMixin, CreateView):  # новое изменение
    form_class = NotesForm
    template_name = 'notes_page/new_post.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView): # Новый класс
    form_class = NotesForm
    model = Notes
    template_name = 'notes_page/post_edit.html'
    success_url = reverse_lazy('home')


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Notes
    template_name = 'notes_page/post_delete.html'
    success_url = reverse_lazy('home')


class CompleteView(LoginRequiredMixin, DetailView):
    model = Notes
    template_name = 'notes_page/post_complete.html'

class ListCompleteView(LoginRequiredMixin, ListView):
    model = Notes
    template_name = 'notes_page/home_complete.html'

templates/notes_page/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'notes_page/style.css' %}">
    <link rel="stylesheet" href="{% static 'notes_page/span_color.css' %}">
    {% block link %}
    {% endblock %}
</head>
<body>
{% if user.is_authenticated %}
    <div class="main">
        <h1 class="neon text-center">Привет, {{ request.user.username }}</h1>
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">

            <div class="collapse navbar-collapse" id="navbarNav" style="justify-content: center; align-items: center">
              <ul class="navbar-nav">
                <li class="nav-item" style="display: flex">
                        <a href="{% url "logout" %}" class="color1">

                            Выйти
                        </a>
                </li>
                <li class="nav-item">
                  <a href="{% url "home" %}">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>Главная
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url "home_complete" %}">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>завершенные
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
            {% block content %}
            {% endblock %}
    </div>
{% endif %}

</div>
</body>
</html>

templates/notes_page/home.html
{% extends 'notes_page/base.html' %}

{% block content %}
    <div class="container" style="display: flex;justify-content: center;align-items: center;flex-direction: column-reverse;">
        {% for note in notes_list %}
            {% if note.task_complete == False %}
                <div style="width: 500px">
                    <a href="note/{{ note.id }}" {% if note.important == False %}style="text-decoration: none; width: 500px"{% else %}style="text-decoration: none; width: 500px" class="color2"{% endif %}>
                        <h6>{{ note.time_create|date:'j M. H:i' }}<p>{{ note.time_create|date:'Y' }}</p></h6>
                        <h4>{{ note.name }}</h4><br>
                        {% if note.descriptions %}
                            <h6 class="h5-cl">{{ note.descriptions }}</h6>
                        {% else %}
                            <h6>Описания нет</h6>
                        {% endif %}
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="pagination container" style="display: flex; justify-content: center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}">Назад</a>
            {% endif %}


            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Следующий</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>



    <div class="container" style="display: flex;justify-content: center;align-items: center;flex-direction: column;">
        <a href="{% url 'post_new' %}" class="small new_color2 text-center">
            <span class="new_color"></span>
            <span class="new_color"></span>
            <span class="new_color"></span>
            <span class="new_color"></span>добавить заметку</a>
    </div>
{% endblock %}

templates/notes_page/home_complete.html
{% extends 'notes_page/base.html' %}

{% block content %}
    <div class="container" style="display: flex;justify-content: center;align-items: center;flex-direction: column-reverse;">
        {% for note in notes_list %}
            {% if note.task_complete == True %}
                <div style="width: 500px">
                    <a href="{% url 'post_complete' note.id %}" {% if note.important == False %}style="text-decoration: none; width: 500px"{% else %}style="text-decoration: none; width: 500px" class="color2"{% endif %}>
                        <h6>{{ note.datecompleted }}</h6><br>
                        <h4>{{ note.name }}</h4><br>
                        {% if note.descriptions %}
                            <h6 class="h5-cl">{{ note.descriptions }}</h6>
                        {% else %}
                            <h6>Описания нет</h6>
                        {% endif %}
                    </a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/notes_page/new_post.html
{% extends 'notes_page/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'notes_page/form.css' %}">
{% endblock %}

{% block content %}
        <div style="display: flex;justify-content: center;">
            <div class="login-box mt-5">
                <h1>Новая заметка</h1>
                <form action="" method="post">{% csrf_token %}
                        {{ form.as_p }}
                    <style>
                        h1 {
                            color: #0022ff;
                            text-shadow:
                                0px 0px 10px #0022ff,
                                1px 1px 20px #0022ff,
                                -1px -1px 50px #0022ff
                        }
                    </style>
                    <div style="display: flex;flex-direction: column;">
                      <div><input type="submit" value="Сохранить" class="but"/></div>
                      <div><a href="{% url 'home' %}" class="none none2"><input type="button" value="назад" class="but"/></a></div>
                    </div>
                </form>

            </div>
        </div>

{% endblock %}

templates/notes_page/post_complete.html
{% extends 'notes_page/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'notes_page/form.css' %}">
{% endblock %}

{% block content %}
    <div class="container">

            <div {% if notes.important == False %}class='cont'{% else %}class='cont2'{% endif %}>
                <h2 {% if notes.important == False %}class='neonText2'{% else %}class='neonText'{% endif %}>{{ notes.name }}</h2><br>
                {{ notes.descriptions|linebreaks }}<br>
                <style>
                    {% if notes.important == True %}
                        p {
                            color: #fff;
                            text-shadow: var(--flick-small-text-shadow);
                        }
                        {% else %}
                        p {
                            color: #fff;
                              text-shadow: var(--flick-big-text-shadow);
                        }
                        {% endif %}
                </style>
                {% if notes.important %}
                    <p {% if notes.important == False %}class='neonText2'{% else %}class='neonText'{% endif %}>Важно</p>
                {% else %}
                    <p {% if notes.important == False %}class='neonText2'{% else %}class='neonText'{% endif %}>Не важно</p>
                {% endif %}

            </div>
    <div style="display: flex;justify-content: center;"><a class="none" href="{% url 'home_complete' %}"><button type="button" class="but2">назад</button></a></div>
    </div>
{% endblock %}

templates/notes_page/post_delete.html
{% extends 'notes_page/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'notes_page/form.css' %}">
{% endblock %}

{% block content %}
    <div class="container" style="display: flex;justify-content: center;align-items: center;flex-direction: column;">
        <div>
            <h1 class="neonText">Вы действительно хотите удалить заметку?</h1>
            <form action="" method="post" class="text-center mt-5">{% csrf_token %}
              <button type="submit" class="but2">Да уверен</button>
                <div style="display: flex;justify-content: center;"><a class="none" href="{% url 'post_detail' notes.id %}"><button type="button" class="but2">назад</button></a></div>
                <style>
                    .none {
                        margin: 0;
                    }
                </style>
            </form>
        </div>
    </div>
{% endblock %}

templates/notes_page/post_detail.html
{% extends 'notes_page/base.html' %}
{% load static %}

{% block link %}
    <link rel="stylesheet" href="{% static 'notes_page/form.css' %}">
{% endblock %}

{% block content %}

    <div>

        <div {% if notes.important == False %}class='cont container-sm'{% else %}class='cont2 container-sm'{% endif %}>
            <h2 {% if notes.important == False %}class='neonText2'{% else %}class='neonText'{% endif %}>{{ notes.name }}</h2>
            <br>
            {{ notes.descriptions|linebreaks }}<br>
                <style>
                    {% if notes.important == True %}
                        p {
                            color: #fff;
                            text-shadow: var(--flick-small-text-shadow);
                        }
                        {% else %}
                        p {
                            color: #fff;
                              text-shadow: var(--flick-big-text-shadow);
                        }
                        {% endif %}
                </style>
            {% if notes.important %}
                <p {% if notes.important == False %}class='neonText2'{% else %}class='neonText'{% endif %}>Важно</p>
            {% else %}
                <p {% if notes.important == False %}class='neonText2'{% else %}class='neonText'{% endif %}>Не важно</p>
            {% endif %}
        </div>
        <div style="display: flex;justify-content: center;" class="mb-3">
            <a href='{% url 'post_edit' notes.id %}'>Редактировать заметку</a>
            <a href='{% url 'post_delete' notes.id %}'>Удалить заметку</a><br>
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="neonText" style="display: flex;justify-content: center;">{{ form.as_p }}</div><br>
            <style>
                label {
                    color: #ff0000;
                    text-shadow: 0 0 5px #f40303,
                        0 0 25px #a90000,
                        0 0 50px #ea1111,
                        0 0 200px #ff1616;
                        }
            </style>
            <div style="display: flex;justify-content: center;"><button type="submit" class="but2">Сохранить</button>

                <style>
                    .but2 {
                        margin-top: 0;
                    }
                </style>
            </div>
            <div style="display: flex;justify-content: center;"><a class="none" href="{% url 'home' %}"><button type="button" class="but2">назад</button></a></div>
        </form>
    </div>
{% endblock %}

templates/notes_page/post_edit.html
{% extends 'notes_page/base.html' %}
{% load static %}
{% block link %}
    <link rel="stylesheet" href="{% static 'notes_page/form.css' %}">
{% endblock %}

{% block content %}
    <div class="login-box mt-5">
            <h1>Редактировать заметку</h1>
            <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <style>
                    h1 {
                        color: #0022ff;
                        text-shadow:
                            0px 0px 10px #0022ff,
                            1px 1px 20px #0022ff,
                            -1px -1px 50px #0022ff
                    }
                    textarea {
                        max-height: 300px;
                    }
                    .login-box {
                        position: absolute;
                        top: 50%;
                        left: 50%;
                        transform: translate(-50%, -50%);
                    }
                </style>
                <div style="display: flex;flex-direction: column;">
                <div><button type="submit" class="but">Сохранить</button></div>
                <div><a href="{% url 'post_detail' notes.id %}" class="none none2"><input type="button" value="назад" class="but"/></a></div>
                </div>
            </form>
    </div>
{% endblock %}